### PR TITLE
Updating the package to support the latest SOCI Release under Debian

### PR DESCRIPTION
**Pull request by OniDaito**
Removed the lines for CDBS as using cmake sort of makes them redundant.
Removed the GCC suffix as I suspect it's not needed.
Changed the Licence line to reflect it's new position.
Removed the patches as I don't think they are needed anymore.

### CODE REVIEW

**Comment by mloskot** [comment]
I'd be happy to grant you write permissions to the soci-pkg, so  you can merge this and future updates on your own. Let me know if you're interested.

**Comment by denisarnaud** [comment]
Yes, that would be perfect, thanks!

**Comment by OniDaito** [comment]
Thanks! That would be great! We'd like to eventually get SOCI into the official debian again. Whilst that may not be possible for Jessie, a custom repos online would be a very handy thing. Cheers

**Comment by mloskot** [comment]
@OniDaito The invitation sent. Welcome to the team!

**Comment by akashihi** [comment]
Does it really need to require libmysqlclient15-dev or can we just use  libmysqlclient-dev virtual package and keep it compatible to future releases?

**Comment by OniDaito** [comment]
I'm not seeing anywhere specifically where that should be pulled in. Agreed it shouldn't be specific.

**Pull request merged**
